exclude:
  - "app/views/sessions/_oauth_buttons.html.haml"

linters:
  ClassesBeforeIds:
    enabled: false
  SpaceInsideHashAttributes:
    enabled: false
  RuboCop:
    rubocop_config:
      Layout/SpaceInsideParens:
        Enabled: false
      Layout/SpaceInsideArrayLiteralBrackets:
        Enabled: false
      Layout/SpaceInsideHashLiteralBraces:
        Enabled: false
  LineLength:
    max: 160
  InlineStyles:
    enabled: false
  ViewLength:
    max: 200
