linters:
  ClassesBeforeIds:
    enabled: false
  SpaceInsideHashAttributes:
    enabled: false
  RuboCop:
    rubocop_config:
      Layout/SpaceInsideArrayLiteralBrackets:
        Enabled: false
  LineLength:
    max: 160
  InlineStyles:
    enabled: false
  ViewLength:
    max: 200
